network_identifier:
  blockchain: Zcoin
  network: mainnet
currency:
  symbol: XZC
  decimals: 8
server:
  port: 8080
node:
  endpoint: 127.0.0.1:8888
  tlsEnabled: false
  username: test
  password: test
version:
  rosettaVersion: 1.3.1
  ZcoinVersion: 0.14.0.3
