network_identifier:
  blockchain: digibyte
  network: mainnet
currency:
  symbol: DGB
  decimals: 8
server:
  port: 8080
node:
  endpoint: 127.0.0.1:22222
  tlsEnabled: false
  username: test
  password: test
version:
  rosettaVersion: 1.3.1
  digibyteVersion: 7.17.2
